### ISSUE TITLE
mechanism to clear cache?

### ISSUE THREAD

**Issue by cboettig** [eoda-dev/py-maplibregl#103]
Is there a way to adjust the cache expiration for data urls?  

In general, in maplibre data resources come from an external url, which can make it a bit more difficult to update maps dynamically.  If I understand correctly, the typical solution (provided we can update the remote data source) is to expire the cache so that the new data loads, i.e. set

```
'Cache-Control: 'max-age=0'
```

(perhaps as discussed in https://github.com/mapbox/mapbox-gl-js/issues/2633#issuecomment-576050636 ? I'm a bit out of my depth on this one).

**Comment by crazycapivara** [comment]
@cboettig In most case you do not need to update your data with `Map.set_data` but use filters instead which makes it very comfortable:

```python
m = Map(...)
m.add_layer(...)

# Update your layer using a filter on the 'growth' property of your source
filter_expression = [">=", ["get", "growth"], 0.5] # only show features where growth >= 0.5

m.set_filter("your_layer_id", filter_expression)
```

Furthermore, the upcoming release come with seamless support for  `geopandas` data frames for vector data sources.

See also [changelog for unreleased version](https://github.com/eodaGmbH/py-maplibregl/blob/feature/color-utils/docs/changelog.md).

**Comment by cboettig** [comment]
oh fantastic! native support for geopandas is much simpler than cache exploration.

Thanks for mentioning the filters, I need to spend more time exploring the performance implications there. Do you know if maplibre js is able to execute those as a range request without transferring all the data?  For the moment I'm relying on duckdb to do my filters, it's quite good at filtering 150gb parquet file in seconds, and figured I that would be difficult purely client-side.  But in at least some cases I'm probably better off using the filters. 

That filter syntax is really nice too. @giswqs -- is something like `m.set_filter()` possible in leafmap.maplibre wrapper?  Guess that feels a bit more pythonic than putting it all in the style dict (though I guess something about configuring the map entirely with a dict is also kinda elegant in it's own way).

**Comment by crazycapivara** [comment]
@cboettig Yes, range requests are possible:

```json
["all", [">=", ["get", "growth"], 0.2], ["<=", ["get", "growth"], 0.5]]
```

In the next release I also added some helper functions for creating these kind of expressions / filters as you can [see in this example](https://github.com/eodaGmbH/py-maplibregl/blob/feature/color-utils/examples/filters.py).

In general, for large datasets it is good practice to use url sources, because maplibre only loads / queries the feature in the current viewport and for the filters set, it never loads all of the data.

**Comment by crazycapivara** [comment]
@cboettig I would the close this issue now if it is solved for you with the expressions!?

**Comment by cboettig** [comment]
Thanks @crazycapivara .  Yes, filtering with range requests is good, and as you say scales considerably better than embedding the geojson directly like what we get from passing the geopandas to pydeck instead of a URL.
